### ISSUE TITLE
[function request] create a c# wrap for UVAtlas

### ISSUE THREAD

**Issue by orangeagain** [amerkoleci/Vortice.UVAtlas#1]
This .Net binding is so cool, but to this day c# still lack UV unwrap funtion
UV unwrap is important part of game engine.Especially to generate light map uv and program generated mesh's uv.
Fortunately, mircosoft open source code of [UVAtlas](https://github.com/microsoft/UVAtlas)form DirectX.
I have sponsored this idea. Would you like to bind that?

**Comment by orangeagain** [comment]
> @orangeagain if you have some C# code I can test the library with please share it, thanks :)

no problem,I will madetest soon.

**Comment by orangeagain** [comment]
here is design for c++ side.only 2 funtions we need.
[UVatlasInterface.zip](https://github.com/amerkoleci/Vortice.UVAtlas/files/6289605/UVatlasInterface.zip)

If we implement c++ side, we can use this nuget to verify result.
[UVAtlas.NET(close source)](https://www.nuget.org/packages/UVAtlas.NET/)

**Comment by amerkoleci** [comment]
Here you go,
Latest commit contains the function you need (wrapped from DirectXMesh) and the UVAtlasCreate.

Please test it in your scenario and I plan to add all remaining DirectXMesh and UVAtlas functions.

**Comment by orangeagain** [comment]
Different result each time.might be memory error somewhere.
I use UVATLAS.Net to compare result.UVATLAS.Net works well in unity,
but dotnet core can't import DLL. I'm not figure out yet.
[Vortice.UVAtlas.Tests.zip](https://github.com/amerkoleci/Vortice.UVAtlas/files/6305190/Vortice.UVAtlas.Tests.zip)

**Comment by amerkoleci** [comment]
Fixed more marshal issues, can you try now please?

**Comment by orangeagain** [comment]
> Fixed more marshal issues, can you try now please?

sorry for my dealy.much things during this period of time.
Your library works great！result is correct！
I will continue to test,If I find bug I will inform you.

**Comment by amerkoleci** [comment]
Perfect, once we're fine I can add remaining DirectXMesh functions and UVAtlas as well.

**Comment by orangeagain** [comment]
new question coming:
I'm building uvatlas for linux arm64 and MacOs and iOS.
I use cmake and make build *.a file,How to build dynamic link file like your /src/native/UVAtlas.dll ?

**Comment by amerkoleci** [comment]
Non windows platform is out of scope for this project or Vortice.Windows in general, probably DirectXMesh won't compile on Linux or other platforms, maybe ask at https://github.com/microsoft/UVAtlas?

Thanks

**Comment by orangeagain** [comment]
I successed compiled on linux.
[DirectXTex, DirectXMesh and UVAtlas now support Linux](https://walbourn.github.io/directxtex-directxmesh-and-uvatlas-now-support-linux/)
I alreadly asked offical,here:
[Support for Windows Subsystem for Linux](https://github.com/microsoft/UVAtlas/pull/56)
the problem is how to compile to DLL.
would you tell me how to compile dll on windows?

**Comment by amerkoleci** [comment]
Just checkout my fork https://github.com/amerkoleci/Vortice.UVAtlas and build, it will generate dll instead of static lib.
