### ISSUE TITLE
How to export function form UVatlas source code?

### ISSUE THREAD

**Issue by orangeagain** [amerkoleci/Vortice.UVAtlas#2]
I need to build dynamic library for linux.
I notic this dll `Vortice.UVAtlas/src/Vortice.UVAtlas/native/win-x64/UVAtlas.dll`
Exposed this fountions:
```
ComputeNormals_UInt16
ComputeNormals_UInt32
GenerateAdjacencyAndPointReps_UInt16
GenerateAdjacencyAndPointReps_UInt32
uvatlas_create_uint32
uvatlas_delete
UVAtlasApplyRemap
```
Can you open source how to build this Dll?

**Comment by amerkoleci** [comment]
Not sure what the issue is :)

The source code is here: https://github.com/amerkoleci/UVAtlas

Just open in visual studio and compile the UVAtlas project, not sure how it would work on linux.

**Comment by orangeagain** [comment]
This link is CSharp project.
I need c++ Dll project,please.
[https://github.com/amerkoleci/UVAtlas](https://github.com/amerkoleci/UVAtlas)

**Comment by amerkoleci** [comment]
Seriously, where did you see CSharp project there? :)

**Comment by orangeagain** [comment]
Sorry, my fault. I mass `amerkoleci/UVAtlas` and `amerkoleci/Vortice.UVAtlas`
Great work by the way.
