### ISSUE TITLE
Can I use "T[]" instead "Span<T>"?

### ISSUE THREAD

**Issue by orangeagain** [amerkoleci/Vortice.UVAtlas#3]
.net standard 2.0 not support `Span<T>`,so I want to replace `Span<T>`.
I changed all `Span<T>` to `T[]`, and looks work well.
I'm not sure is this way are safe?

**Comment by amerkoleci** [comment]
Thats not true, you need to add System.Memory package (https://github.com/amerkoleci/Vortice.UVAtlas/blob/main/src/Vortice.UVAtlas/Vortice.UVAtlas.csproj#L9)

I can add overloads which takes array, stay tuned.

**Comment by orangeagain** [comment]
Actually I use it on unity, but unity not support .net standerd 2.1,and not support Nuget package.

**Comment by amerkoleci** [comment]
Fixed now with https://github.com/amerkoleci/Vortice.UVAtlas/commit/11a03ad160c1d7bfbeebd8029abc7cf4da2ddcb4
