### ISSUE TITLE
Replace "Unsafe.CopyBlockUnaligned()"

### ISSUE THREAD

**Issue by orangeagain** [amerkoleci/Vortice.UVAtlas#4]
Unity not support `Unsafe.CopyBlockUnaligned() in UVAtlas.cs:line:74`
Could you use `Buffer.MemoryCopy()` or other to instead of it?

Many cpoy way I found here:[Improve BlockCopy performance](https://github.com/neuecc/MessagePack-CSharp/issues/117)

**Comment by amerkoleci** [comment]
Can you please tell me which net target does unity3d supports?

**Comment by amerkoleci** [comment]
Ok, but the target of this project is netstandard2.0 and not unity3d, if not supporting nuget, feel free to fork the project and keep it aligned
